Rokolabs.Library/Rokolabs.Library.UIWeb/Controllers/NewspaperController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rokolabs.Library.Bll.Interfaces;
using Rokolabs.Library.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rokolabs.Library.UIWeb.Controllers
{
    public class NewspaperController : Controller
    {
        private readonly ILogger<BookController> _logger;
        private readonly INewspaperService _newspaperService;
        private readonly ICityService _cityService;
        private readonly IPublishingOfficeService _publishingOfficeService;

        public NewspaperController(ILogger<BookController> logger, INewspaperService newspaperService, ICityService cityService, IPublishingOfficeService publishingOfficeService)
        {
            _logger = logger;
            _newspaperService = newspaperService;
            _cityService = cityService;
            _publishingOfficeService = publishingOfficeService;
        }


        // GET: NewspaperController
        public ActionResult Index()
        {
            var newspapers = _newspaperService.GetAllNewspapers();
            return View(newspapers);
        }

        [HttpPost]
        public ActionResult Index(Newspaper newspaper)
        {
            List<Newspaper> newspapers;
            if (newspaper.Title == null)
                newspapers = _newspaperService.GetAllNewspapers();
            else
                newspapers = _newspaperService.SearchNewspaper(newspaper);
            return View(newspapers);
        }

        // GET: NewspaperController/Details/5
        public ActionResult Details(Newspaper newspaper)
        {
            return View(newspaper);
        }

        // GET: NewspaperController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewspaperController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Newspaper newspaper)
        {
            try
            {
                newspaper.CityID = CheckEntityInDatabase(newspaper.CityName, _cityService);
                newspaper.PublishingOfficeID = CheckEntityInDatabase(newspaper.PublishingOfficeName, _publishingOfficeService);
                _newspaperService.InsertNewspaper(newspaper);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NewspaperController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: NewspaperController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NewspaperController/Delete/5
        public ActionResult Delete(Newspaper newspaper)
        {
            return View(newspaper);
        }

        // POST: NewspaperController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int paperID, IFormCollection collection)
        {
            try
            {
                _newspaperService.DeleteNewspaper(paperID);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public int CheckEntityInDatabase(string name, IDefiningEntity entityRepostitory)
        {
            int id = entityRepostitory.FindThisEntity(name);
            if (id == 0)
            {
                id = entityRepostitory.InsertThisEntity(name);
            }
            return id;
        }
    }
}

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Newspaper/Create.cshtml
@model Rokolabs.Library.Data.Newspaper

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Newspaper</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityName" class="control-label"></label>
                <input asp-for="CityName" class="form-control" />
                <span asp-validation-for="CityName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishingOfficeName" class="control-label"></label>
                <input asp-for="PublishingOfficeName" class="form-control" />
                <span asp-validation-for="PublishingOfficeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISSN" class="control-label"></label>
                <input asp-for="ISSN" class="form-control" />
                <span asp-validation-for="ISSN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaperNumber" class="control-label"></label>
                <input asp-for="PaperNumber" class="form-control" />
                <span asp-validation-for="PaperNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfPublishing" class="control-label"></label>
                <input asp-for="YearOfPublishing" class="form-control" />
                <span asp-validation-for="YearOfPublishing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PagesCount" class="control-label"></label>
                <input asp-for="PagesCount" class="form-control" />
                <span asp-validation-for="PagesCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Newspaper/Delete.cshtml
@model Rokolabs.Library.Data.Newspaper

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this newspaper?</h3>
<div>
    <h4>Newspaper info</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CityName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CityName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingOfficeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishingOfficeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISSN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISSN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaperNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaperNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearOfPublishing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearOfPublishing)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PagesCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PagesCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
        @Html.HiddenFor(model => model.PaperID)
    </form>
</div>

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Newspaper/Details.cshtml
@model Rokolabs.Library.Data.Newspaper

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Newspaper</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CityName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CityName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingOfficeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishingOfficeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISSN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISSN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaperNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaperNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearOfPublishing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearOfPublishing)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PagesCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PagesCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Newspaper/Index.cshtml
@model IEnumerable<Rokolabs.Library.Data.Newspaper>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Newspapers in library</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Newspaper" asp-action="Index">
    <p class="searching-box">
        Title: <input type="text" name="Title" />
        <input type="submit" value="Search" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISSN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PagesCount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISSN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PagesCount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", item) |
                @Html.ActionLink("Details", "Details", item) |
                @Html.ActionLink("Delete", "Delete", item)
            </td>
        </tr>
}
    </tbody>
</table>