Rokolabs.Library/Rokolabs.Library.UIWeb/Controllers/BookController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rokolabs.Library.Bll.Interfaces;
using Rokolabs.Library.Data;
using Sentry;
using System;
using System.Collections.Generic;

namespace Rokolabs.Library.UIWeb.Controllers
{
    public class BookController : Controller
    {
        private readonly ILogger<BookController> _logger;
        private readonly IBookService _bookService;
        private readonly ICityService _cityService;
        private readonly IPublishingOfficeService _publishingOfficeService;
        private readonly IHub _hub;
        
        public BookController(ILogger<BookController> logger, IBookService bookService, ICityService cityService, IPublishingOfficeService publishingOfficeService, IHub hub)
        {
            _logger = logger;
            _bookService = bookService;
            _cityService = cityService;
            _publishingOfficeService = publishingOfficeService;
            _hub = hub;
        }

        // GET: BookController
        public ActionResult Index()
        {
            //var books = _bookService.GetAllBooks();
            List<Book> books = default(List<Book>);
            Wrapper.Watch(() => { books = _bookService.GetAllBooks(); }, _hub, "load-all-books", "transaction");
            return View(books);
        }

        [HttpPost]
        public ActionResult Index(Book book, int[] authors)
        {
            List<Book> books = default(List<Book>);
            if (book.Title == null)
                books = _bookService.GetAllBooks();
            else
            {
                //books = _bookService.SearchBook(book);
                Wrapper wrapper = new Wrapper();
                books = wrapper.Watch(() => _bookService.SearchBook(book), _hub, "search-all-books", "transaction");
                //Wrapper.Watch(() => { books = _bookService.SearchBook(book); }, _hub, "search-all-books", "transaction");
            }
            return View(books);
        }

        // GET: BookController/Details/5
        public ActionResult Details(Book book)
        {
            return View(book);
        }

        // GET: BookController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book book)
        {

            Wrapper.Watch(() => { 
                book.CityID = CheckEntityInDatabase(book.CityName, _cityService);
                book.PublishingOfficeID = CheckEntityInDatabase(book.PublishingOfficeName, _publishingOfficeService);
                _bookService.InsertBook(book); 
            }, 
            _hub, "creating-a-book", "transaction");
            return RedirectToAction(nameof(Index));
            //var transaction = _hub.GetSpan();
            //var child1 = transaction.StartChild("creating-a-book");
            //try
            //{
            //    book.CityID = CheckEntityInDatabase(book.CityName, _cityService);
            //    book.PublishingOfficeID = CheckEntityInDatabase(book.PublishingOfficeName, _publishingOfficeService);
            //    _bookService.InsertBook(book);
            //    child1.Finish(SpanStatus.Ok);
            //    return RedirectToAction(nameof(Index));
            //}
            //catch
            //{
            //    child1.Finish(SpanStatus.Aborted);
            //    return View();
            //}
        }

        // GET: BookController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Delete/5
        public ActionResult Delete(Book book)
        {
            return View(book);
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int bookId, IFormCollection collection)
        {
            try
            {
                _bookService.DeleteBook(bookId);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return View();
            }
        }

        public int CheckEntityInDatabase(string name, IDefiningEntity entityRepostitory)
        {
            int id = entityRepostitory.FindThisEntity(name);
            if (id == 0)
            {
                id = entityRepostitory.InsertThisEntity(name);
            }
            return id;
        }
    }
}

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Book/Create.cshtml
@model Rokolabs.Library.Data.Book

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityName" class="control-label">City of publication</label>
                <input asp-for="CityName" class="form-control" />
                <span asp-validation-for="CityName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishingOfficeName" class="control-label">Publishing office</label>
                <input asp-for="PublishingOfficeName" class="form-control" />
                <span asp-validation-for="PublishingOfficeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfPublishing" class="control-label">Year of publishing</label>
                <input asp-for="YearOfPublishing" class="form-control" />
                <span asp-validation-for="YearOfPublishing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PagesCount" class="control-label">Pages</label>
                <input asp-for="PagesCount" class="form-control" />
                <span asp-validation-for="PagesCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Book/Delete.cshtml
@model Rokolabs.Library.Data.Book

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this book?</h3>
<div>
    <h4>Book Info</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CityName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CityName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingOfficeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishingOfficeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorsInfo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AuthorsInfo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.YearOfPublishing)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.YearOfPublishing)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PagesCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PagesCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
        @Html.HiddenFor(model => model.BookId)
    </form>
</div>

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Book/Details.cshtml
@model Rokolabs.Library.Data.Book

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CityName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CityName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingOfficeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishingOfficeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorsInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorsInfo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearOfPublishing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearOfPublishing)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PagesCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PagesCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Book/Index.cshtml
@model IEnumerable<Rokolabs.Library.Data.Book>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>

<h1>Books in library</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Book" asp-action="Index">
    <p class="searching-box">
        Title: <input type="text" name="Title"  style="width: 50%"/>
        Authors: <select class="js-example-basic-multiple" name="authors[]" id="authors" style="width: 25%" multiple="multiple">
                  <option value="AL">Author</option>
                  <option value="WY">Example</option>
                </select>
        <input type="submit" value="Search" />
    </p>
</form>

@*<p>Authors:</p>
<div><select class="js-example-basic-multiple" name="authors[]" id="authors" style="width: 50%" multiple="multiple">
  <option value="AL">Author</option>
  <option value="WY">Example</option>
</select>
<input type="submit" value="Search" />
</div>*@

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PagesCount)
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PagesCount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", item) |
                @Html.ActionLink("Details", "Details", item) |
                @Html.ActionLink("Delete", "Delete", item)
            </td>
        </tr>
        }
    </tbody>
</table>



@section Scripts {
    @{await Html.RenderPartialAsync("Select2ScriptsPartial");}
}

<script>
    $(document).ready(function () {
        $('#authors').select2({
            ajax: {
                url: 'https://localhost:5001/author/get',
                data: function (params) {
                    var query = {
                        search: params.term,
                        type: 'public'
                    }
                    return query;
                },
                processResults: function (data) {
                    return {
                        results: data
                    };
                }
            }
        });
    });
</script>