Rokolabs.Library/Rokolabs.Library.UIWeb/Controllers/PatentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rokolabs.Library.Bll.Interfaces;
using Rokolabs.Library.Data;
using System.Collections.Generic;

namespace Rokolabs.Library.UIWeb.Controllers
{
    public class PatentController : Controller
    {
        private readonly ILogger<PatentController> _logger;
        private readonly IPatentService _patentService;
        private readonly ICountryService _countryService;

        public PatentController(ILogger<PatentController> logger, IPatentService patentService, ICountryService countryService)
        {
            _logger = logger;
            _patentService = patentService;
            _countryService = countryService;
        }
        // GET: PatentController
        public ActionResult Index()
        {
            var patents = _patentService.GetAllPatents();
            return View(patents);
        }

        [HttpPost]
        public ActionResult Index(Patent patent)
        {
            List<Patent> patents;
            if (patent.Title == null)
                patents = _patentService.GetAllPatents();
            else
                patents = _patentService.SearchPatent(patent);
            return View(patents);
        }

        // GET: PatentController/Details/5
        public ActionResult Details(Patent patent)
        {
            return View(patent);
        }

        // GET: PatentController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PatentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Patent patent)
        {
            try
            {
                patent.CountryID = CheckEntityInDatabase(patent.CountryName, _countryService);
                _patentService.InsertPatent(patent);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PatentController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PatentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PatentController/Delete/5
        public ActionResult Delete(Patent patent)
        {
            return View(patent);
        }

        // POST: PatentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int patentID, IFormCollection collection)
        {
            try
            {
                _patentService.DeletePatent(patentID);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public int CheckEntityInDatabase(string name, IDefiningEntity entityRepostitory)
        {
            int id = entityRepostitory.FindThisEntity(name);
            if (id == 0)
            {
                id = entityRepostitory.InsertThisEntity(name);
            }
            return id;
        }
    }
}

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Patent/Create.cshtml
@model Rokolabs.Library.Data.Patent

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Patent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryName" class="control-label"></label>
                <input asp-for="CountryName" class="form-control" />
                <span asp-validation-for="CountryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatentRegistrationNumber" class="control-label"></label>
                <input asp-for="PatentRegistrationNumber" class="form-control" />
                <span asp-validation-for="PatentRegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationDate" class="control-label"></label>
                <input asp-for="ApplicationDate" class="form-control" />
                <span asp-validation-for="ApplicationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicationDate" class="control-label"></label>
                <input asp-for="PublicationDate" class="form-control" />
                <span asp-validation-for="PublicationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PagesCount" class="control-label"></label>
                <input asp-for="PagesCount" class="form-control" />
                <span asp-validation-for="PagesCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorsInfo" class="control-label"></label>
                <input asp-for="AuthorsInfo" class="form-control" />
                <span asp-validation-for="AuthorsInfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Patent/Delete.cshtml
@model Rokolabs.Library.Data.Patent

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this patent?</h3>
<div>
    <h4>Patent Info</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatentRegistrationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatentRegistrationNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplicationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublicationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublicationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PagesCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PagesCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorsInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorsInfo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
        @Html.HiddenFor(model => model.PatentID)
    </form>
</div>

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Patent/Details.cshtml
@model Rokolabs.Library.Data.Patent

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Patent</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PatentRegistrationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PatentRegistrationNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplicationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublicationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublicationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PagesCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PagesCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorsInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorsInfo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Rokolabs.Library/Rokolabs.Library.UIWeb/Views/Patent/Index.cshtml
@model IEnumerable<Rokolabs.Library.Data.Patent>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Patents in library</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Patent" asp-action="Index">
    <p class="searching-box">
        Title: <input type="text" name="Title" />
        <input type="submit" value="Search" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PatentRegistrationNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PagesCount)
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PatentRegistrationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PagesCount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", item) |
                @Html.ActionLink("Details", "Details", item) |
                @Html.ActionLink("Delete", "Delete", item)
            </td>
        </tr>
        }
    </tbody>
</table>